In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv(r"D:\Intan\Documents\Code Clinic\Code Clinic Week 2\Regiment.csv")
df1

      Regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd      Alii             3             70

In [3]:
df2 = pd.read_csv(r"D:\Intan\Documents\Code Clinic\Code Clinic Week 2\Regiment_DateBirth.csv")
df2

        Name  Birth Date
0     Miller  12/05/1985
1   Jacobson  30/05/1987
2        Ali  04/06/1990
3     Milner  01/08/1989
4      Cooze  12/09/1985
5      Jacon  30/05/1986
6     Ryaner  04/02/1990
7       Sone  01/01/1989
8      Sloan  12/05/1995
9      Piger  30/05/1986
10     Riani  09/03/1990
11      Alii  01/06/1979

In [4]:
df1=df1.rename(columns={"name":"Name"})

#### Question 1 - Write a code to merge the two dataframes by a common column - name and create df as a single dataframe

In [5]:
df = pd.merge(left=df1,right=df2,on='Name')
df

      Regiment company      Name  preTestScore  postTestScore  Birth Date
0   Nighthawks     1st    Miller             4             25  12/05/1985
1   Nighthawks     1st  Jacobson            24             94  30/05/1987
2   Nighthawks     2nd       Ali            31             57  04/06/1990
3   Nighthawks     2nd    Milner             2             62  01/08/1989
4     Dragoons     1st     Cooze             3             70  12/09/1985
5     Dragoons     1st     Jacon             4             25  30/05/1986
6     Dragoons     2nd    Ryaner            24             94  04/02/1990
7     Dragoons     2nd      Sone            31             57  01/01/1989
8       Scouts     1st     Sloan             2             62  12/05/1995
9       Scouts     1st     Piger             3             70  30/05/1986
10      Scouts     2nd     Riani             2             62  09/03/1990
11      Scouts     2nd      Alii             3             70  01/06/1979

In [6]:
# Another Way to do 
# df = pd.merge(left=df1,right=df2,left_on='name',right_on='name',how='inner')
df

      Regiment company      Name  preTestScore  postTestScore  Birth Date
0   Nighthawks     1st    Miller             4             25  12/05/1985
1   Nighthawks     1st  Jacobson            24             94  30/05/1987
2   Nighthawks     2nd       Ali            31             57  04/06/1990
3   Nighthawks     2nd    Milner             2             62  01/08/1989
4     Dragoons     1st     Cooze             3             70  12/09/1985
5     Dragoons     1st     Jacon             4             25  30/05/1986
6     Dragoons     2nd    Ryaner            24             94  04/02/1990
7     Dragoons     2nd      Sone            31             57  01/01/1989
8       Scouts     1st     Sloan             2             62  12/05/1995
9       Scouts     1st     Piger             3             70  30/05/1986
10      Scouts     2nd     Riani             2             62  09/03/1990
11      Scouts     2nd      Alii             3             70  01/06/1979

#### Question 2 - create a new column with name "improvement" representing the improvement made by soldiers during training.

In [7]:
df['improvement'] = df['postTestScore'] - df['preTestScore']
df

,Regiment,company,Name,preTestScore,postTestScore,Birth Date,improvement
0,Nighthawks,1st,Miller,4,25,12/05/1985,21
1,Nighthawks,1st,Jacobson,24,94,30/05/1987,70
2,Nighthawks,2nd,Ali,31,57,04/06/1990,26
3,Nighthawks,2nd,Milner,2,62,01/08/1989,60
4,Dragoons,1st,Cooze,3,70,12/09/1985,67
5,Dragoons,1st,Jacon,4,25,30/05/1986,21
6,Dragoons,2nd,Ryaner,24,94,04/02/1990,70
7,Dragoons,2nd,Sone,31,57,01/01/1989,26
8,Scouts,1st,Sloan,2,62,12/05/1995,60
9,Scouts,1st,Piger,3,70,30/05/1986,67
10,Scouts,2nd,Riani,2,62,09/03/1990,60
11,Scouts,2nd,Alii,3,70,01/06/1979,67

#### Question 3 - Write code to convert the name of soldiers

In [8]:
m = "Intan"
m.upper()

'INTAN'

In [9]:
m = "Intan"
m.title()

'Intan'

In [12]:
df['Name'] = df['Name'].str.title()

In [13]:
df

,Regiment,company,Name,preTestScore,postTestScore,Birth Date,improvement
0,Nighthawks,1st,Miller,4,25,12/05/1985,21
1,Nighthawks,1st,Jacobson,24,94,30/05/1987,70
2,Nighthawks,2nd,Ali,31,57,04/06/1990,26
3,Nighthawks,2nd,Milner,2,62,01/08/1989,60
4,Dragoons,1st,Cooze,3,70,12/09/1985,67
5,Dragoons,1st,Jacon,4,25,30/05/1986,21
6,Dragoons,2nd,Ryaner,24,94,04/02/1990,70
7,Dragoons,2nd,Sone,31,57,01/01/1989,26
8,Scouts,1st,Sloan,2,62,12/05/1995,60
9,Scouts,1st,Piger,3,70,30/05/1986,67
10,Scouts,2nd,Riani,2,62,09/03/1990,60
11,Scouts,2nd,Alii,3,70,01/06/1979,67

#### Question 4 - Write code to extract age of soldiers from the date of birth column

In [14]:
import datetime as dt
today = dt.datetime.today()

In [16]:
df['Birth Date'] = pd.to_datetime(df['Birth Date'])

C:\Users\Intan\AppData\Local\Temp\ipykernel_152520\4190504690.py:1: UserWarning: Parsing '30/05/1987' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df['Birth Date'] = pd.to_datetime(df['Birth Date'])
C:\Users\Intan\AppData\Local\Temp\ipykernel_152520\4190504690.py:1: UserWarning: Parsing '30/05/1986' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df['Birth Date'] = pd.to_datetime(df['Birth Date'])

In [17]:
def dob2age(dob):
    age = today - dob
    age = age.days/365
    return round(age)

In [18]:
df['Age'] = df['Birth Date'].apply(dob2age)
df

,Regiment,company,Name,preTestScore,postTestScore,Birth Date,improvement,Age
0,Nighthawks,1st,Miller,4,25,1985-12-05,21,40
1,Nighthawks,1st,Jacobson,24,94,1987-05-30,70,39
2,Nighthawks,2nd,Ali,31,57,1990-04-06,26,36
3,Nighthawks,2nd,Milner,2,62,1989-01-08,60,37
4,Dragoons,1st,Cooze,3,70,1985-12-09,67,40
5,Dragoons,1st,Jacon,4,25,1986-05-30,21,40
6,Dragoons,2nd,Ryaner,24,94,1990-04-02,70,36
7,Dragoons,2nd,Sone,31,57,1989-01-01,26,37
8,Scouts,1st,Sloan,2,62,1995-12-05,60,30
9,Scouts,1st,Piger,3,70,1986-05-30,67,40
10,Scouts,2nd,Riani,2,62,1990-09-03,60,36
11,Scouts,2nd,Alii,3,70,1979-01-06,67,47

#### Question 5 - Standardize all column name - remove spaces, capitalize

In [21]:
df.columns = df.columns.str.strip().str.title()
print(df.columns)

Index(['Regiment', 'Company', 'Name', 'Pretestscore', 'Posttestscore',
       'Birth Date', 'Improvement', 'Age'],
      dtype='object')

#### Question 6 - write code to create a categorical attribute for Age
- if age <34 = low
- if age is b/w 34 to 40 - medium
- if age>40 - high

In [23]:
df['Age_Cat_Bin'] = pd.cut(df['Age'],bins=[0,34,40,100],labels=['Low','Medium','High'])
df

,Regiment,Company,Name,Pretestscore,Posttestscore,Birth Date,Improvement,Age,age_cat,Age_Cat_Bin
0,Nighthawks,1st,Miller,4,25,1985-12-05,21,40,Medium,Medium
1,Nighthawks,1st,Jacobson,24,94,1987-05-30,70,39,Medium,Medium
2,Nighthawks,2nd,Ali,31,57,1990-04-06,26,36,Medium,Medium
3,Nighthawks,2nd,Milner,2,62,1989-01-08,60,37,Medium,Medium
4,Dragoons,1st,Cooze,3,70,1985-12-09,67,40,Medium,Medium
5,Dragoons,1st,Jacon,4,25,1986-05-30,21,40,Medium,Medium
6,Dragoons,2nd,Ryaner,24,94,1990-04-02,70,36,Medium,Medium
7,Dragoons,2nd,Sone,31,57,1989-01-01,26,37,Medium,Medium
8,Scouts,1st,Sloan,2,62,1995-12-05,60,30,Low,Low
9,Scouts,1st,Piger,3,70,1986-05-30,67,40,Medium,Medium
10,Scouts,2nd,Riani,2,62,1990-09-03,60,36,Medium,Medium
11,Scouts,2nd,Alii,3,70,1979-01-06,67,47,High,High

In [26]:
def age_category(age):
    if pd.isna(age):
        return 'Unknown'
    elif age <= 34:
        return 'Low'
    elif age <= 40:
        return 'Medium'
    else:
        return 'High'

df['Age_Cat_Func'] = df['Age'].apply(age_category)

In [27]:
df

,Regiment,Company,Name,Pretestscore,Posttestscore,Birth Date,Improvement,Age,age_cat,Age_Cat_Bin,Age_Cat-Func,Age_Cat_Func
0,Nighthawks,1st,Miller,4,25,1985-12-05,21,40,Medium,Medium,Medium,Medium
1,Nighthawks,1st,Jacobson,24,94,1987-05-30,70,39,Medium,Medium,Medium,Medium
2,Nighthawks,2nd,Ali,31,57,1990-04-06,26,36,Medium,Medium,Medium,Medium
3,Nighthawks,2nd,Milner,2,62,1989-01-08,60,37,Medium,Medium,Medium,Medium
4,Dragoons,1st,Cooze,3,70,1985-12-09,67,40,Medium,Medium,Medium,Medium
5,Dragoons,1st,Jacon,4,25,1986-05-30,21,40,Medium,Medium,Medium,Medium
6,Dragoons,2nd,Ryaner,24,94,1990-04-02,70,36,Medium,Medium,Medium,Medium
7,Dragoons,2nd,Sone,31,57,1989-01-01,26,37,Medium,Medium,Medium,Medium
8,Scouts,1st,Sloan,2,62,1995-12-05,60,30,Low,Low,Low,Low
9,Scouts,1st,Piger,3,70,1986-05-30,67,40,Medium,Medium,Medium,Medium
10,Scouts,2nd,Riani,2,62,1990-09-03,60,36,Medium,Medium,Medium,Medium
11,Scouts,2nd,Alii,3,70,1979-01-06,67,47,High,High,High,High

#### Question 7 - which regiment is the best regiment after the traiing completion?

In [32]:
df.groupby(['Regiment'])['Posttestscore'].mean()

Regiment
Dragoons      61.5
Nighthawks    59.5
Scouts        66.0
Name: Posttestscore, dtype: float64

#### Question 8 - which company of which regiment is the best company after the training completion?

In [33]:
df.groupby(['Regiment','Company'])['Posttestscore'].mean()

Regiment    Company
Dragoons    1st        47.5
            2nd        75.5
Nighthawks  1st        59.5
            2nd        59.5
Scouts      1st        66.0
            2nd        66.0
Name: Posttestscore, dtype: float64

#### Question 9 - which regiment has made mximum improvement during the training?

In [34]:

df.groupby(['Regiment'])['Improvement'].mean()

Regiment
Dragoons      46.00
Nighthawks    44.25
Scouts        63.50
Name: Improvement, dtype: float64

In [ ]:
# saving your result to excel
df.groupby(['regiment'])['improvement'].mean().to_excel("D:\Intan\Documents\Code Clinic\Code Clinic Week 2\results.xlsx")