In [1]:
import pandas as pd

In [30]:
#import data
reward = pd.read_csv('D:\Intan\Documents\Code Clinic\Code Clinic Week 2\RewardsData.csv')
reg = pd.read_csv('D:\Intan\Documents\Code Clinic\Code Clinic Week 2\Regiment.csv')
regb = pd.read_csv('D:\Intan\Documents\Code Clinic\Code Clinic Week 2\Regiment_DateBirth.csv')

<>:2: SyntaxWarning: invalid escape sequence '\I'
<>:3: SyntaxWarning: invalid escape sequence '\I'
<>:4: SyntaxWarning: invalid escape sequence '\I'
<>:2: SyntaxWarning: invalid escape sequence '\I'
<>:3: SyntaxWarning: invalid escape sequence '\I'
<>:4: SyntaxWarning: invalid escape sequence '\I'
C:\Users\Intan\AppData\Local\Temp\ipykernel_51060\462782029.py:2: SyntaxWarning: invalid escape sequence '\I'
  reward = pd.read_csv('D:\Intan\Documents\Code Clinic\Code Clinic Week 2\RewardsData.csv')
C:\Users\Intan\AppData\Local\Temp\ipykernel_51060\462782029.py:3: SyntaxWarning: invalid escape sequence '\I'
  reg = pd.read_csv('D:\Intan\Documents\Code Clinic\Code Clinic Week 2\Regiment.csv')
C:\Users\Intan\AppData\Local\Temp\ipykernel_51060\462782029.py:4: SyntaxWarning: invalid escape sequence '\I'
  regb = pd.read_csv('D:\Intan\Documents\Code Clinic\Code Clinic Week 2\Regiment_DateBirth.csv')

# Step-by-Step Data Transformation Sample



### Discovery

```python
df.head()          # show first 5 rows
df.tail()          # show last rows
df.shape           # (rows, columns)
df.columns         # column names
df.info()          # structure + datatypes + missing values
df.describe()      # statistical summary (numeric columns)
df.sample(5)       # random rows
df.isna().sum()    # count missing values
df.nunique()       # unique values per column
df.value_counts()  # frequency distribution
```

In [17]:
reward.shape

(7252, 11)

In [14]:
#view first 5 records
reward.head()

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42,ClassOf2025
1,2,NaN,Los Angeles,Colorado,90210,320,320,0,8/19/2020 11:15,4/13/2022 14:28,ClassOf2025|apple
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A

In [15]:
reward.tail()

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
7247,7238,NaN,NaN,NaN,NaN,320,320,0,6/28/2022 21:02,6/30/2022 12:04,Student|GraduateStudent
7248,7239,NaN,NaN,NaN,NaN,310,310,0,6/28/2022 22:43,6/28/2022 22:43,Student|GraduateStudent
7249,7240,3/3/1997,NaN,NaN,NaN,410,410,0,6/30/2022 12:47,6/30/2022 12:48,Student|GraduateStudent
7250,7241,NaN,NaN,NaN,NaN,310,310,0,6/30/2022 20:38,6/30/2022 20:39,Student|GraduateStudent
7251,7242,NaN,NaN,NaN,NaN,310,310,0,7/1/2022 2:27,7/1/2022 2:42,Student|GraduateStudent

In [19]:
reward.describe()

           User ID  Available Points  Total Points Earned  Points Spent
count  7252.000000       7252.000000           7252.00000   7252.000000
mean   3621.871484       1406.701737           1596.89203    191.383067
std    2091.085954       2031.637229           2531.73693   1223.108659
min       1.000000          0.000000            100.00000      0.000000
25%    1811.750000        400.000000            400.00000      0.000000
50%    3619.500000        735.000000            800.00000      0.000000
75%    5432.250000       1550.000000           1710.00000      0.000000
max    7242.000000      52165.000000          59525.00000  57800.000000

In [12]:
#Check null value
reward.isna()

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen               221
Tags                      0
dtype: int64

In [20]:
reward.isna().sum()

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen               221
Tags                      0
dtype: int64

In [33]:
reward.isna().sum() / len(reward) * 100

User ID                 0.000000
Birthdate              83.838941
City                   95.449531
State                  95.449531
Zip                    95.449531
Available Points        0.000000
Total Points Earned     0.000000
Points Spent            0.000000
Joined On               0.000000
Last Seen               3.047435
Tags                    0.000000
dtype: float64

In [34]:
reward['Last Seen']

0       12/16/2021 17:42
1        4/13/2022 14:28
2        4/21/2021 10:54
3        6/30/2022 22:22
4       12/30/2020 10:57
              ...
7247     6/30/2022 12:04
7248     6/28/2022 22:43
7249     6/30/2022 12:48
7250     6/30/2022 20:39
7251       7/1/2022 2:42
Name: Last Seen, Length: 7252, dtype: str

In [37]:
reward['Last Seen']=pd.to_datetime(reward['Last Seen'])

In [38]:
reward['Last Seen']

0      2021-12-16 17:42:00
1      2022-04-13 14:28:00
2      2021-04-21 10:54:00
3      2022-06-30 22:22:00
4      2020-12-30 10:57:00
               ...
7247   2022-06-30 12:04:00
7248   2022-06-28 22:43:00
7249   2022-06-30 12:48:00
7250   2022-06-30 20:39:00
7251   2022-07-01 02:42:00
Name: Last Seen, Length: 7252, dtype: datetime64[us]

In [40]:
reward['Last Seen'].describe()

count                          7031
mean     2022-02-13 01:49:27.128431
min             2020-10-12 14:38:00
25%             2022-01-18 22:06:00
50%             2022-03-14 10:01:00
75%             2022-04-21 20:56:00
max             2022-07-01 08:36:00
Name: Last Seen, dtype: object

In [43]:
reward['Last Seen'].max()

Timestamp('2022-07-01 08:36:00')

In [44]:
reward['Last Seen'].min()

Timestamp('2020-10-12 14:38:00')

In [46]:
reward['Last Seen'].median()

Timestamp('2022-03-14 10:01:00')

In [48]:
reward['Last Seen'].mode()

0   2022-05-26 20:06:00
Name: Last Seen, dtype: datetime64[us]

### Structuring

```python
df.fillna()
df.dropna()
df.replace()
df.rename(columns={"old":"new"})
df.astype({"age":"int"})
df.sort_values("age")
df.set_index("id")
df.reset_index()
df.melt()          # wide → long
df.pivot()         # long → wide
df.pivot_table()
df.stack()
df.unstack()
```

### Cleaning

#### Handling Missing Value
```python
df.isna()
df.fillna(0)
df.fillna(method="fill")
df.dropna()
```

#### Drop Duplicate
```python
df.duplicated()
df.drop_duplicates()
```

#### Fixing Value
```python
df.replace("unknown", np.nan)
df["age"] = df["age"].clip(lower=0)
df["city"] = df["city"].str.lower()
df["city"] = df["city"].str.strip()
```

#### Filtering Value
```python
df = df[df["age"] > 18]
df.query("age > 18")
```

In [52]:
reward['Last Seen'] = reward['Last Seen'].fillna(reward['Last Seen'].min())

In [53]:
reward.isna().sum() / len(reward) * 100

User ID                 0.000000
Birthdate              83.838941
City                   95.449531
State                  95.449531
Zip                    95.449531
Available Points        0.000000
Total Points Earned     0.000000
Points Spent            0.000000
Joined On               0.000000
Last Seen               0.000000
Tags                    0.000000
dtype: float64

In [56]:
reward=reward.rename(columns={"Last Seen":"Last_Seen"})

In [57]:
reward.head()

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last_Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,ClassOf2025
1,2,NaN,Los Angeles,Colorado,90210,320,320,0,8/19/2020 11:15,2022-04-13 14:28:00,ClassOf2025|apple
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A

In [58]:
# drop record missing value and assign to new data frame
reward_nonull = reward.dropna()
reward_nonull

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last_Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,ClassOf2025
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,GraduateStudent|admin
...,...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00,Student|ClassOf2026
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00,Student|ClassOf2023
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00,Student|GraduateStudent
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00,Student|GraduateStudent
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00,Student|ClassOf2026

In [59]:
reward_nonull.isna().sum() / len(reward) * 100

User ID                0.0
Birthdate              0.0
City                   0.0
State                  0.0
Zip                    0.0
Available Points       0.0
Total Points Earned    0.0
Points Spent           0.0
Joined On              0.0
Last_Seen              0.0
Tags                   0.0
dtype: float64

In [62]:
# drop unnecessary column
reward_nonull = reward_nonull.drop(columns='Tags')

In [63]:
reward_nonull

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last_Seen
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00
...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00

In [65]:
reward_nonull['City'].value_counts()

City
Winston-Salem     36
Winston Salem     25
Winston Salem     10
Charlotte          5
Lutherville        3
                  ..
Cleveland          1
Rome               1
Delhi              1
Clemmons           1
Guaynabo           1
Name: count, Length: 85, dtype: int64

In [66]:
# If you want to show all result whenever you do analysis

In [ ]:
# pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_rows')

In [105]:
reward_nonull_city = reward_nonull['City'].unique()

In [106]:
reward_nonull_city

<StringArray>
[       'Minneapolis',             'Merida',      'Winston_Salem',
                  'G',        'Thomasville',           'Bethesda',
       'Jacksonville',             'Durham',            'Orleans',
         'Rocky Hill',             'Delran',          'Milwaukee',
 'Lincoln University',              'Perry',            'Atlanta',
          'Charlotte',             'Austin',        'Chapel Hill',
             'Summit',      'Downers Grove',       'Terrace Park',
        'Lutherville',            'Wyckoff',       'Mt. Pleasant',
          'Northport',         'Pittsburgh',        'Bakersfield',
           'Waukegan',         'Marblehead',          'Morganton',
             'Locust',        'Mooresville',             'Dallas',
             'Sharon',          'Larchmont',               'Lmao',
       'Indian Trail',          'Littleton',              'Dover',
       'West Chester',              'Edina',             'Supply',
         'Greensboro',         'Whitesboro',                'Rex',
             'Aurora',            'Malvern',       'Huntersville',
             'Bourne',            'Belmont',             'Waxhaw',
       'Libertyville',             'Weston',         'Louisville',
          'Nashville',        'Gainesville',           'Westport',
         'Jamesville',            'Memphis',       'Palmetto Bay',
       'Ormond Beach',         'Fort Myers',            'Oakwood',
    'Manhattan Beach',      'Winston Salem',            'Duxbury',
         'San Marcos', 'Palm Beach Gardens',         'Walkertown',
            'Valrico',             'Clovis',          'Smithtown',
          'Cleveland',               'Rome',              'Delhi',
           'Clemmons',           'Guaynabo']
Length: 77, dtype: str

In [107]:
reward_nonull_city = sorted(reward_nonull_city)
reward_nonull_city

['Atlanta',
 'Aurora',
 'Austin',
 'Bakersfield',
 'Belmont',
 'Bethesda',
 'Bourne',
 'Chapel Hill',
 'Charlotte',
 'Clemmons',
 'Cleveland',
 'Clovis',
 'Dallas',
 'Delhi',
 'Delran',
 'Dover',
 'Downers Grove',
 'Durham',
 'Duxbury',
 'Edina',
 'Fort Myers',
 'G',
 'Gainesville',
 'Greensboro',
 'Guaynabo',
 'Huntersville',
 'Indian Trail',
 'Jacksonville',
 'Jamesville',
 'Larchmont',
 'Libertyville',
 'Lincoln University',
 'Littleton',
 'Lmao',
 'Locust',
 'Louisville',
 'Lutherville',
 'Malvern',
 'Manhattan Beach',
 'Marblehead',
 'Memphis',
 'Merida',
 'Milwaukee',
 'Minneapolis',
 'Mooresville',
 'Morganton',
 'Mt. Pleasant',
 'Nashville',
 'Northport',
 'Oakwood',
 'Orleans',
 'Ormond Beach',
 'Palm Beach Gardens',
 'Palmetto Bay',
 'Perry',
 'Pittsburgh',
 'Rex',
 'Rocky Hill',
 'Rome',
 'San Marcos',
 'Sharon',
 'Smithtown',
 'Summit',
 'Supply',
 'Terrace Park',
 'Thomasville',
 'Valrico',
 'Walkertown',
 'Waukegan',
 'Waxhaw',
 'West Chester',
 'Weston',
 'Westport',
 'Whitesboro',
 'Winston Salem',
 'Winston_Salem',
 'Wyckoff']

In [108]:
# replace the variation
reward_nonull.replace(
    {'City': ['Winston Salem', 'Winston Salem ', 'Winston salem', 'Winston salem ',
              'Winston-Salem', 'Winston-Salem ', 'Winston-Salem, NC', 'Winston-salem']},
    'Winston Salem',
    inplace=True
)

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last_Seen
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00
3,4,4/16/1990,Winston_Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00
4,5,3/24/1994,Winston_Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00
...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00
7229,7220,8/7/1999,Winston_Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00
7239,7230,5/18/1999,Winston_Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00

In [109]:
reward_nonull['City'].value_counts()

City
Winston_Salem    79
Charlotte         6
Lutherville       3
Greensboro        3
Atlanta           2
                 ..
Cleveland         1
Rome              1
Delhi             1
Clemmons          1
Guaynabo          1
Name: count, Length: 77, dtype: int64

In [110]:
# remove all leading and trailing space from cuty column
reward_nonull['City']=reward_nonull['City'].str.strip()

In [111]:
reward_nonull['City']=reward_nonull['City'].str.title()

In [112]:
reward_nonull_city = reward_nonull['City'].unique()
reward_nonull_city = sorted(reward_nonull_city)
reward_nonull_city

['Atlanta',
 'Aurora',
 'Austin',
 'Bakersfield',
 'Belmont',
 'Bethesda',
 'Bourne',
 'Chapel Hill',
 'Charlotte',
 'Clemmons',
 'Cleveland',
 'Clovis',
 'Dallas',
 'Delhi',
 'Delran',
 'Dover',
 'Downers Grove',
 'Durham',
 'Duxbury',
 'Edina',
 'Fort Myers',
 'G',
 'Gainesville',
 'Greensboro',
 'Guaynabo',
 'Huntersville',
 'Indian Trail',
 'Jacksonville',
 'Jamesville',
 'Larchmont',
 'Libertyville',
 'Lincoln University',
 'Littleton',
 'Lmao',
 'Locust',
 'Louisville',
 'Lutherville',
 'Malvern',
 'Manhattan Beach',
 'Marblehead',
 'Memphis',
 'Merida',
 'Milwaukee',
 'Minneapolis',
 'Mooresville',
 'Morganton',
 'Mt. Pleasant',
 'Nashville',
 'Northport',
 'Oakwood',
 'Orleans',
 'Ormond Beach',
 'Palm Beach Gardens',
 'Palmetto Bay',
 'Perry',
 'Pittsburgh',
 'Rex',
 'Rocky Hill',
 'Rome',
 'San Marcos',
 'Sharon',
 'Smithtown',
 'Summit',
 'Supply',
 'Terrace Park',
 'Thomasville',
 'Valrico',
 'Walkertown',
 'Waukegan',
 'Waxhaw',
 'West Chester',
 'Weston',
 'Westport',
 'Whitesboro',
 'Winston Salem',
 'Winston_Salem',
 'Wyckoff']